import type { Metadata } from "next";
import { Epilogue, Press_Start_2P } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Echo | Chaos Theory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${epilogue.variable} ${pressStart2P.variable} antialiased`}>
      <body>
        <header>
        <div className="absolute top-0 w-full p-4 md:p-8 flex flex-col md:flex-row items-center justify-between text-white">
        <Image src="/echo-logo.png" alt="Echo Logo" width={114} height={41}/>
        <nav aria-label="main navigation" className="flex font-bold gap-4">
          <Link href="/">home</Link>
          <Link href="/echo-lounge">echo lounge</Link>
          <Link href="/subscribe">subscribe</Link>
        </nav>
        </div>
        <div className="absolute uppercase bottom-0 w-full md:w-fit p-4 md:p-8 flex md:flex-col justify-center md:justify-start text-sm gap-2 font-light tracking-wider">
          <Link href="/#music">MUSIC</Link>
          <span className="inline md:hidden">|</span>
          <Link href="/#tour">TOUR</Link>
          <span className="inline md:hidden">|</span>
          <Link href="/#merch">MERCH</Link>
          <span className="inline md:hidden">|</span>
          <Link href="/#kiriban">KIRIBAN</Link>
        </div>

      </header>
        {children}
      </body>
    </html>
  );
}
