import type { Metadata } from "next";
import { Epilogue, Press_Start_2P } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Echo | Chaos Theory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${epilogue.variable} ${pressStart2P.variable} antialiased`}>
      <header className="flex items-center justify-between p-8 text-white">
        <Image src="/echo-logo.png" alt="Echo Logo" width={114} height={41}/>
        <nav aria-label="main navigation" className="flex font-bold gap-4">
          <Link href="/">home</Link>
          <Link href="/echo-lounge">echo lounge</Link>
          <Link href="/subscribe">subscribe</Link>
        </nav>
        <div className="absolute uppercase bottom-0 flex md:flex-col text-sm pb-8 gap-2 font-light">
          <Link href="/#music">MUSIC</Link>
          <Link href="/#tour">TOUR</Link>
          <Link href="/#merch">MERCH</Link>
          <Link href="/#kiriban">KIRIBAN</Link>
        </div>

      </header>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
